// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "_mlcomtools.h"

/////////////////////////////////////////////////////////////////////////////
// C_MLComTools

IMPLEMENT_DYNCREATE(C_MLComTools, CWnd)

/////////////////////////////////////////////////////////////////////////////
// C_MLComTools properties

/////////////////////////////////////////////////////////////////////////////
// C_MLComTools operations

void C_MLComTools::ShowAbout()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void C_MLComTools::ReceivePacket()
{
	InvokeHelper(0x60030056, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

BOOL C_MLComTools::EncryptFile(BSTR* strFileName, BSTR* strBuffer, short* intLength)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PBSTR VTS_PBSTR VTS_PI2;
	InvokeHelper(0x6003005a, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strFileName, strBuffer, intLength);
	return result;
}

CString C_MLComTools::WinDir()
{
	CString result;
	InvokeHelper(0x6003005b, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString C_MLComTools::WinSysDir()
{
	CString result;
	InvokeHelper(0x6003005c, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

long C_MLComTools::ConvertStrhToDec(BSTR* strToConvert)
{
	long result;
	static BYTE parms[] =
		VTS_PBSTR;
	InvokeHelper(0x6003005d, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		strToConvert);
	return result;
}

long C_MLComTools::ConvertStrdToDec(BSTR* strToConvert)
{
	long result;
	static BYTE parms[] =
		VTS_PBSTR;
	InvokeHelper(0x6003005e, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		strToConvert);
	return result;
}

void C_MLComTools::TwipsToPixel(short* intXvalue, short* intYvalue)
{
	static BYTE parms[] =
		VTS_PI2 VTS_PI2;
	InvokeHelper(0x6003005f, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 intXvalue, intYvalue);
}

void C_MLComTools::PixelToTwips(short* intXvalue, short* intYvalue)
{
	static BYTE parms[] =
		VTS_PI2 VTS_PI2;
	InvokeHelper(0x60030060, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 intXvalue, intYvalue);
}

long C_MLComTools::IsActive(VARIANT* hprog)
{
	long result;
	static BYTE parms[] =
		VTS_PVARIANT;
	InvokeHelper(0x60030062, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		hprog);
	return result;
}

VARIANT C_MLComTools::SuspendActivateExe(BSTR* strNameExe)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_PBSTR;
	InvokeHelper(0x60030063, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		strNameExe);
	return result;
}

CString C_MLComTools::addLRC8toString(BSTR* strPacket, short* initValue)
{
	CString result;
	static BYTE parms[] =
		VTS_PBSTR VTS_PI2;
	InvokeHelper(0x60030064, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		strPacket, initValue);
	return result;
}

short C_MLComTools::cLRC8str(BSTR* strPacket, short* intStart, short* intEnd, short* intInitial)
{
	short result;
	static BYTE parms[] =
		VTS_PBSTR VTS_PI2 VTS_PI2 VTS_PI2;
	InvokeHelper(0x60030065, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		strPacket, intStart, intEnd, intInitial);
	return result;
}

short C_MLComTools::cLRC8file(BSTR* strFileName, long* longStart, long* longEnd, short* intInitial)
{
	short result;
	static BYTE parms[] =
		VTS_PBSTR VTS_PI4 VTS_PI4 VTS_PI2;
	InvokeHelper(0x60030066, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		strFileName, longStart, longEnd, intInitial);
	return result;
}

CString C_MLComTools::addCRC16toString(BSTR* strPacket, short* initValue, short* Polynomial)
{
	CString result;
	static BYTE parms[] =
		VTS_PBSTR VTS_PI2 VTS_PI2;
	InvokeHelper(0x60030068, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		strPacket, initValue, Polynomial);
	return result;
}

long C_MLComTools::cCRC16str(BSTR* strPacket, short* intStart, short* intEnd, short* intInitial, short* intPolynomial)
{
	long result;
	static BYTE parms[] =
		VTS_PBSTR VTS_PI2 VTS_PI2 VTS_PI2 VTS_PI2;
	InvokeHelper(0x60030069, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		strPacket, intStart, intEnd, intInitial, intPolynomial);
	return result;
}

long C_MLComTools::cCRC16file(BSTR* strFileName, long* longStart, long* longEnd, short* intInitial, short* intPolynomial)
{
	long result;
	static BYTE parms[] =
		VTS_PBSTR VTS_PI4 VTS_PI4 VTS_PI2 VTS_PI2;
	InvokeHelper(0x6003006a, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		strFileName, longStart, longEnd, intInitial, intPolynomial);
	return result;
}

short C_MLComTools::cCHECKSUMstr(BSTR* strPacket, short* intStart, short* intEnd, short* intInitial)
{
	short result;
	static BYTE parms[] =
		VTS_PBSTR VTS_PI2 VTS_PI2 VTS_PI2;
	InvokeHelper(0x6003006c, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		strPacket, intStart, intEnd, intInitial);
	return result;
}

short C_MLComTools::cCHECKSUMfile(BSTR* strFileName, long* longStart, long* longEnd, short* intInitial)
{
	short result;
	static BYTE parms[] =
		VTS_PBSTR VTS_PI4 VTS_PI4 VTS_PI2;
	InvokeHelper(0x6003006d, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		strFileName, longStart, longEnd, intInitial);
	return result;
}

BOOL C_MLComTools::TestStrHexa(BSTR* str)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PBSTR;
	InvokeHelper(0x60030070, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		str);
	return result;
}

BOOL C_MLComTools::TestStrDec(BSTR* str)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PBSTR;
	InvokeHelper(0x60030071, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		str);
	return result;
}

CString C_MLComTools::AddParityString(BSTR* str)
{
	CString result;
	static BYTE parms[] =
		VTS_PBSTR;
	InvokeHelper(0x60030072, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		str);
	return result;
}

CString C_MLComTools::SupParityString(BSTR* str)
{
	CString result;
	static BYTE parms[] =
		VTS_PBSTR;
	InvokeHelper(0x60030073, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		str);
	return result;
}

CString C_MLComTools::cStr1DtoDec(BSTR* strPacket, short* intStart, short* intEnd)
{
	CString result;
	static BYTE parms[] =
		VTS_PBSTR VTS_PI2 VTS_PI2;
	InvokeHelper(0x60030074, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		strPacket, intStart, intEnd);
	return result;
}

CString C_MLComTools::cStr2DtoDec(BSTR* strPacket, short* intStart, short* intEnd)
{
	CString result;
	static BYTE parms[] =
		VTS_PBSTR VTS_PI2 VTS_PI2;
	InvokeHelper(0x60030075, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		strPacket, intStart, intEnd);
	return result;
}

CString C_MLComTools::cStr3DtoDec(BSTR* strPacket, short* intStart, short* intEnd)
{
	CString result;
	static BYTE parms[] =
		VTS_PBSTR VTS_PI2 VTS_PI2;
	InvokeHelper(0x60030076, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		strPacket, intStart, intEnd);
	return result;
}

CString C_MLComTools::cStr1HtoDec(BSTR* strPacket, short* intStart, short* intEnd)
{
	CString result;
	static BYTE parms[] =
		VTS_PBSTR VTS_PI2 VTS_PI2;
	InvokeHelper(0x60030077, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		strPacket, intStart, intEnd);
	return result;
}

CString C_MLComTools::cStr2HtoDec(BSTR* strPacket, short* intStart, short* intEnd)
{
	CString result;
	static BYTE parms[] =
		VTS_PBSTR VTS_PI2 VTS_PI2;
	InvokeHelper(0x60030078, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		strPacket, intStart, intEnd);
	return result;
}

CString C_MLComTools::c2DecToAsc(BSTR* strPacket, short* intStart, short* intEnd)
{
	CString result;
	static BYTE parms[] =
		VTS_PBSTR VTS_PI2 VTS_PI2;
	InvokeHelper(0x60030079, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		strPacket, intStart, intEnd);
	return result;
}

CString C_MLComTools::c3DecToAsc(BSTR* strPacket, short* intStart, short* intEnd)
{
	CString result;
	static BYTE parms[] =
		VTS_PBSTR VTS_PI2 VTS_PI2;
	InvokeHelper(0x6003007a, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		strPacket, intStart, intEnd);
	return result;
}

CString C_MLComTools::c2HexToAsc(BSTR* strPacket, short* intStart, short* intEnd)
{
	CString result;
	static BYTE parms[] =
		VTS_PBSTR VTS_PI2 VTS_PI2;
	InvokeHelper(0x6003007b, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		strPacket, intStart, intEnd);
	return result;
}

BOOL C_MLComTools::CommInit(short* intPort, BSTR* strSettings)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PI2 VTS_PBSTR;
	InvokeHelper(0x6003007d, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		intPort, strSettings);
	return result;
}

BOOL C_MLComTools::CommOpen()
{
	BOOL result;
	InvokeHelper(0x6003007e, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL C_MLComTools::CommClose()
{
	BOOL result;
	InvokeHelper(0x6003007f, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL C_MLComTools::SendMessageTestL3000(BSTR* strSend)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PBSTR;
	InvokeHelper(0x60030080, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strSend);
	return result;
}

void C_MLComTools::RecMessageTestL3000(BSTR* strRec, short* intStatus, long* longTimeOut)
{
	static BYTE parms[] =
		VTS_PBSTR VTS_PI2 VTS_PI4;
	InvokeHelper(0x60030081, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strRec, intStatus, longTimeOut);
}

void C_MLComTools::MessageTestL3000(BSTR* strSend, BSTR* strRec, short* intStatus, long* longTimeOut)
{
	static BYTE parms[] =
		VTS_PBSTR VTS_PBSTR VTS_PI2 VTS_PI4;
	InvokeHelper(0x60030082, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strSend, strRec, intStatus, longTimeOut);
}

BOOL C_MLComTools::SendMessage(BSTR* strMessage)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PBSTR;
	InvokeHelper(0x60030083, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strMessage);
	return result;
}

CString C_MLComTools::RecMessage(long* longTimeOut)
{
	CString result;
	static BYTE parms[] =
		VTS_PI4;
	InvokeHelper(0x60030084, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		longTimeOut);
	return result;
}

CString C_MLComTools::Message(BSTR* strMessage, long* longTimeOut)
{
	CString result;
	static BYTE parms[] =
		VTS_PBSTR VTS_PI4;
	InvokeHelper(0x60030085, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		strMessage, longTimeOut);
	return result;
}

CString C_MLComTools::POSMessage()
{
	CString result;
	InvokeHelper(0x60030086, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

VARIANT C_MLComTools::POSAutoIncSequence()
{
	VARIANT result;
	InvokeHelper(0x60030088, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
	return result;
}

CString C_MLComTools::POSAutoMessage(BSTR* Fct, long* lngTimeout)
{
	CString result;
	static BYTE parms[] =
		VTS_PBSTR VTS_PI4;
	InvokeHelper(0x60030089, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		Fct, lngTimeout);
	return result;
}

CString C_MLComTools::POSAutoAuthorization(BSTR* strAmount, BSTR* strCurrency, BSTR* strControl, BSTR* strClass, long* lngTimeout)
{
	CString result;
	static BYTE parms[] =
		VTS_PBSTR VTS_PBSTR VTS_PBSTR VTS_PBSTR VTS_PI4;
	InvokeHelper(0x6003008a, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		strAmount, strCurrency, strControl, strClass, lngTimeout);
	return result;
}

CString C_MLComTools::POSAutoRecording(BSTR* strAmount, BSTR* strCurrency, long* lngTimeout)
{
	CString result;
	static BYTE parms[] =
		VTS_PBSTR VTS_PBSTR VTS_PI4;
	InvokeHelper(0x6003008b, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		strAmount, strCurrency, lngTimeout);
	return result;
}

CString C_MLComTools::POSAutoReceiptMerchant(long* lngTimeout)
{
	CString result;
	static BYTE parms[] =
		VTS_PI4;
	InvokeHelper(0x6003008c, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		lngTimeout);
	return result;
}

CString C_MLComTools::POSAutoSettingExtReader(BSTR* strTrackISO1, BSTR* strTrackISO2, BSTR* strTrackISO3, long* lngTimeout)
{
	CString result;
	static BYTE parms[] =
		VTS_PBSTR VTS_PBSTR VTS_PBSTR VTS_PI4;
	InvokeHelper(0x6003008d, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		strTrackISO1, strTrackISO2, strTrackISO3, lngTimeout);
	return result;
}

CString C_MLComTools::POSAutoReadingCard(BSTR* strReadingType, long* lngTimeout)
{
	CString result;
	static BYTE parms[] =
		VTS_PBSTR VTS_PI4;
	InvokeHelper(0x6003008e, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		strReadingType, lngTimeout);
	return result;
}

CString C_MLComTools::POSAutoDisplayingPinPadRequest(BSTR* strText, BSTR* strInputType, BSTR* strMinLength, BSTR* strMaxLength, BSTR* strInputOffset, long* lngTimeout)
{
	CString result;
	static BYTE parms[] =
		VTS_PBSTR VTS_PBSTR VTS_PBSTR VTS_PBSTR VTS_PBSTR VTS_PI4;
	InvokeHelper(0x6003008f, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		strText, strInputType, strMinLength, strMaxLength, strInputOffset, lngTimeout);
	return result;
}

CString C_MLComTools::POSAutoStatusRequest(long* lngTimeout)
{
	CString result;
	static BYTE parms[] =
		VTS_PI4;
	InvokeHelper(0x60030090, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		lngTimeout);
	return result;
}

CString C_MLComTools::POSAutoSoftwareStatus(long* lngTimeout)
{
	CString result;
	static BYTE parms[] =
		VTS_PI4;
	InvokeHelper(0x60030091, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		lngTimeout);
	return result;
}

CString C_MLComTools::POSAutoClearTransactionFile(long* lngTimeout)
{
	CString result;
	static BYTE parms[] =
		VTS_PI4;
	InvokeHelper(0x60030092, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		lngTimeout);
	return result;
}

CString C_MLComTools::POSAutoAbortOperation(BSTR* strTreatment, long* lngTimeout)
{
	CString result;
	static BYTE parms[] =
		VTS_PBSTR VTS_PI4;
	InvokeHelper(0x60030093, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		strTreatment, lngTimeout);
	return result;
}

CString C_MLComTools::POSAutoSettingEFTConfiguration(BSTR* strCardReader, BSTR* strPrinter, BSTR* strBuzzer, BSTR* strRetroPinPad, long* lngTimeout)
{
	CString result;
	static BYTE parms[] =
		VTS_PBSTR VTS_PBSTR VTS_PBSTR VTS_PBSTR VTS_PI4;
	InvokeHelper(0x60030094, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		strCardReader, strPrinter, strBuzzer, strRetroPinPad, lngTimeout);
	return result;
}

CString C_MLComTools::POSAutoSettingEFTApplication(BSTR* strApplicationCode, BSTR* strEFTNumber, long* lngTimeout)
{
	CString result;
	static BYTE parms[] =
		VTS_PBSTR VTS_PBSTR VTS_PI4;
	InvokeHelper(0x60030095, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		strApplicationCode, strEFTNumber, lngTimeout);
	return result;
}

CString C_MLComTools::POSAutoBeep(BSTR* strNumBeep, long* lngTimeout)
{
	CString result;
	static BYTE parms[] =
		VTS_PBSTR VTS_PI4;
	InvokeHelper(0x60030096, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		strNumBeep, lngTimeout);
	return result;
}

BOOL C_MLComTools::POSAutoSend(BSTR* Fct)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PBSTR;
	InvokeHelper(0x60030097, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Fct);
	return result;
}

BOOL C_MLComTools::POSsend()
{
	BOOL result;
	InvokeHelper(0x60030098, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL C_MLComTools::OpenSession()
{
	BOOL result;
	InvokeHelper(0x60030099, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL C_MLComTools::SendEnq()
{
	BOOL result;
	InvokeHelper(0x6003009a, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL C_MLComTools::WaitAck()
{
	BOOL result;
	InvokeHelper(0x6003009b, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

void C_MLComTools::WaitTimeout(long* longTimeOut)
{
	static BYTE parms[] =
		VTS_PI4;
	InvokeHelper(0x6003009c, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 longTimeOut);
}

void C_MLComTools::WaitTORetry()
{
	InvokeHelper(0x6003009d, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

short C_MLComTools::GetCommPort()
{
	short result;
	InvokeHelper(0x68030053, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetCommPort(short nNewValue)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x68030053, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_MLComTools::GetTOwaitChar()
{
	long result;
	InvokeHelper(0x68030052, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetTOwaitChar(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030052, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_MLComTools::GetTOWaitBetweenCommand()
{
	long result;
	InvokeHelper(0x68030051, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetTOWaitBetweenCommand(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030051, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_MLComTools::GetTOBetweenChar()
{
	long result;
	InvokeHelper(0x68030050, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetTOBetweenChar(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030050, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_MLComTools::GetTOwaitRetry()
{
	long result;
	InvokeHelper(0x6803004f, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetTOwaitRetry(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6803004f, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_MLComTools::GetTOwaitReply()
{
	long result;
	InvokeHelper(0x6803004e, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetTOwaitReply(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6803004e, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

short C_MLComTools::GetRetrySession()
{
	short result;
	InvokeHelper(0x6803004d, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetRetrySession(short nNewValue)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x6803004d, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

short C_MLComTools::GetRetryData()
{
	short result;
	InvokeHelper(0x6803004c, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetRetryData(short nNewValue)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x6803004c, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

CString C_MLComTools::GetCommSettings()
{
	CString result;
	InvokeHelper(0x6803004b, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetCommSettings(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6803004b, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

BOOL C_MLComTools::GetCommPortOpen()
{
	BOOL result;
	InvokeHelper(0x6803004a, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetCommPortOpen(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x6803004a, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

VARIANT C_MLComTools::GetCommInput()
{
	VARIANT result;
	InvokeHelper(0x68030049, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetCommOutput(const VARIANT& newValue)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x68030048, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 &newValue);
}

short C_MLComTools::GetCommInputLen()
{
	short result;
	InvokeHelper(0x68030047, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
	return result;
}

CString C_MLComTools::GetReceiveMessage()
{
	CString result;
	InvokeHelper(0x68030046, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetReceiveMessage(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x68030046, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_MLComTools::GetReceiveError()
{
	CString result;
	InvokeHelper(0x68030045, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetReceiveError(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x68030045, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

void C_MLComTools::SetCommInputLen(short nNewValue)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x68030047, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

void C_MLComTools::SetCommInputMode(short nNewValue)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x68030044, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

CString C_MLComTools::GetPOSNumber()
{
	CString result;
	InvokeHelper(0x68030043, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSNumber(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x68030043, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_MLComTools::GetPOSAmount()
{
	CString result;
	InvokeHelper(0x68030042, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAmount(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x68030042, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

long C_MLComTools::GetPOSTimeout()
{
	long result;
	InvokeHelper(0x68030041, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSTimeout(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030041, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

CString C_MLComTools::GetPOSRep()
{
	CString result;
	InvokeHelper(0x68030040, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSRep(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x68030040, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_MLComTools::GetPOSMode()
{
	CString result;
	InvokeHelper(0x6803003f, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSMode(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6803003f, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_MLComTools::GetPOSAutoTimeOut()
{
	CString result;
	InvokeHelper(0x6803003e, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoTimeOut(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6803003e, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_MLComTools::GetPOSType()
{
	CString result;
	InvokeHelper(0x6803003d, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSType(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6803003d, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_MLComTools::GetPOSDev()
{
	CString result;
	InvokeHelper(0x6803003c, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSDev(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6803003c, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

BOOL C_MLComTools::GetEscapeKeyEnabled()
{
	BOOL result;
	InvokeHelper(0x6803003b, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetEscapeKeyEnabled(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x6803003b, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL C_MLComTools::GetAbortReceive()
{
	BOOL result;
	InvokeHelper(0x6803003a, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetAbortReceive(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x6803003a, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

CString C_MLComTools::GetVersion()
{
	CString result;
	InvokeHelper(0x68030039, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

BOOL C_MLComTools::GetReceiveEnabled()
{
	BOOL result;
	InvokeHelper(0x68030038, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetReceiveEnabled(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x68030038, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL C_MLComTools::GetErrorEnabled()
{
	BOOL result;
	InvokeHelper(0x68030037, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetErrorEnabled(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x68030037, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

CString C_MLComTools::GetEFTposNumber()
{
	CString result;
	InvokeHelper(0x68030036, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString C_MLComTools::GetEFTposStat()
{
	CString result;
	InvokeHelper(0x68030035, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString C_MLComTools::GetEFTposAmount()
{
	CString result;
	InvokeHelper(0x68030034, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString C_MLComTools::GetEFTposMode()
{
	CString result;
	InvokeHelper(0x68030033, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString C_MLComTools::GetEFTposRep()
{
	CString result;
	InvokeHelper(0x68030032, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString C_MLComTools::GetEFTposDev()
{
	CString result;
	InvokeHelper(0x68030031, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString C_MLComTools::GetPOSAutoSequence()
{
	CString result;
	InvokeHelper(0x68030030, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoSequence(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x68030030, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_MLComTools::GetPOSAutoOperation()
{
	CString result;
	InvokeHelper(0x6803002f, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoOperation(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6803002f, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_MLComTools::GetPOSAutoAmount()
{
	CString result;
	InvokeHelper(0x6803002e, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoAmount(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6803002e, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_MLComTools::GetPOSAutoCurrency()
{
	CString result;
	InvokeHelper(0x6803002d, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoCurrency(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6803002d, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_MLComTools::GetPOSAutoControl()
{
	CString result;
	InvokeHelper(0x6803002c, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoControl(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6803002c, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_MLComTools::GetPOSAutoClass()
{
	CString result;
	InvokeHelper(0x6803002b, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoClass(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6803002b, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_MLComTools::GetPOSAutoTrackISO1()
{
	CString result;
	InvokeHelper(0x6803002a, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoTrackISO1(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6803002a, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_MLComTools::GetPOSAutoTrackISO2()
{
	CString result;
	InvokeHelper(0x68030029, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoTrackISO2(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x68030029, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_MLComTools::GetPOSAutoTrackISO3()
{
	CString result;
	InvokeHelper(0x68030028, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoTrackISO3(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x68030028, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_MLComTools::GetPOSAutoReadingType()
{
	CString result;
	InvokeHelper(0x68030027, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoReadingType(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x68030027, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_MLComTools::GetPOSAutoText()
{
	CString result;
	InvokeHelper(0x68030026, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoText(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x68030026, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_MLComTools::GetPOSAutoInputType()
{
	CString result;
	InvokeHelper(0x68030025, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoInputType(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x68030025, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_MLComTools::GetPOSAutoMinLength()
{
	CString result;
	InvokeHelper(0x68030024, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoMinLength(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x68030024, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_MLComTools::GetPOSAutoMaxLength()
{
	CString result;
	InvokeHelper(0x68030023, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoMaxLength(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x68030023, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_MLComTools::GetPOSAutoInputOffset()
{
	CString result;
	InvokeHelper(0x68030022, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoInputOffset(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x68030022, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_MLComTools::GetPOSAutoTreatmentCard()
{
	CString result;
	InvokeHelper(0x68030021, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoTreatmentCard(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x68030021, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_MLComTools::GetPOSAutoCardReader()
{
	CString result;
	InvokeHelper(0x68030020, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoCardReader(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x68030020, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_MLComTools::GetPOSAutoPrinter()
{
	CString result;
	InvokeHelper(0x6803001f, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoPrinter(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6803001f, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_MLComTools::GetPOSAutoBuzzer()
{
	CString result;
	InvokeHelper(0x6803001e, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoBuzzer(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6803001e, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_MLComTools::GetPOSAutoRetroPinPad()
{
	CString result;
	InvokeHelper(0x6803001d, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoRetroPinPad(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6803001d, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_MLComTools::GetPOSAutoApplicationCode()
{
	CString result;
	InvokeHelper(0x6803001c, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoApplicationCode(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6803001c, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_MLComTools::GetPOSAutoEFTNumber()
{
	CString result;
	InvokeHelper(0x6803001b, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoEFTNumber(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6803001b, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_MLComTools::GetPOSAutoData()
{
	CString result;
	InvokeHelper(0x6803001a, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoData(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6803001a, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_MLComTools::GetPOSAutoNumBeep()
{
	CString result;
	InvokeHelper(0x68030019, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoNumBeep(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x68030019, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

long C_MLComTools::GetPOSAutoTOfctAuthorization()
{
	long result;
	InvokeHelper(0x68030018, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoTOfctAuthorization(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030018, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_MLComTools::GetPOSAutoTOfctAuthorizationInter()
{
	long result;
	InvokeHelper(0x68030017, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoTOfctAuthorizationInter(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030017, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_MLComTools::GetPOSAutoTOfctRecording()
{
	long result;
	InvokeHelper(0x68030016, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoTOfctRecording(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030016, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_MLComTools::GetPOSAutoTOfctReceiptMerchant()
{
	long result;
	InvokeHelper(0x68030015, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoTOfctReceiptMerchant(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030015, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_MLComTools::GetPOSAutoTOfctSettingExtReader()
{
	long result;
	InvokeHelper(0x68030014, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoTOfctSettingExtReader(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030014, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_MLComTools::GetPOSAutoTOfctReadingCard()
{
	long result;
	InvokeHelper(0x68030013, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoTOfctReadingCard(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030013, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_MLComTools::GetPOSAutoTOfctDisplayingPinPadRequest()
{
	long result;
	InvokeHelper(0x68030012, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoTOfctDisplayingPinPadRequest(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030012, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_MLComTools::GetPOSAutoTOfctStatusRequest()
{
	long result;
	InvokeHelper(0x68030011, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoTOfctStatusRequest(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030011, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_MLComTools::GetPOSAutoTOfctSoftwareStatus()
{
	long result;
	InvokeHelper(0x68030010, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoTOfctSoftwareStatus(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030010, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_MLComTools::GetPOSAutoTOfctClearTransactionFile()
{
	long result;
	InvokeHelper(0x6803000f, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoTOfctClearTransactionFile(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6803000f, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_MLComTools::GetPOSAutoTOfctAbortOperation()
{
	long result;
	InvokeHelper(0x6803000e, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoTOfctAbortOperation(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6803000e, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_MLComTools::GetPOSAutoTOfctSettingEFTConfiguration()
{
	long result;
	InvokeHelper(0x6803000d, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoTOfctSettingEFTConfiguration(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6803000d, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_MLComTools::GetPOSAutoTOfctSettingEFTApplication()
{
	long result;
	InvokeHelper(0x6803000c, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoTOfctSettingEFTApplication(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6803000c, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_MLComTools::GetPOSAutoTOfctBeep()
{
	long result;
	InvokeHelper(0x6803000b, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoTOfctBeep(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6803000b, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

BOOL C_MLComTools::GetPOSAutoIncSequenceEnabled()
{
	BOOL result;
	InvokeHelper(0x6803000a, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void C_MLComTools::SetPOSAutoIncSequenceEnabled(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x6803000a, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

CString C_MLComTools::GetPOSAutoStatus()
{
	CString result;
	InvokeHelper(0x68030009, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString C_MLComTools::GetPOSAutoStatusCard()
{
	CString result;
	InvokeHelper(0x68030008, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString C_MLComTools::GetPOSAutoApplication()
{
	CString result;
	InvokeHelper(0x68030007, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString C_MLComTools::GetPOSAutoReceipt()
{
	CString result;
	InvokeHelper(0x68030006, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString C_MLComTools::GetPOSAutoPrivate()
{
	CString result;
	InvokeHelper(0x68030005, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString C_MLComTools::GetPOSAutoNbCharacter()
{
	CString result;
	InvokeHelper(0x68030004, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString C_MLComTools::GetPOSAutoString()
{
	CString result;
	InvokeHelper(0x68030003, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString C_MLComTools::GetPOSAutoStatusEFT()
{
	CString result;
	InvokeHelper(0x68030002, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString C_MLComTools::GetPOSAutoCode(short* index)
{
	CString result;
	static BYTE parms[] =
		VTS_PI2;
	InvokeHelper(0x68030001, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		index);
	return result;
}

CString C_MLComTools::GetPOSAutoVersion(short* index)
{
	CString result;
	static BYTE parms[] =
		VTS_PI2;
	InvokeHelper(0x68030000, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		index);
	return result;
}
